return {
	{
		"catppuccin/nvim",
		name = "catppuccin",
		priority = 1000,
		opts = {
			flavour = "mocha",
			background = {
				light = "#eff1f5",
				dark = "#0c1312",
			},
			color_overrides = {
				mocha = {
					base = "#0c1312",
					mantle = "#0c1312",
					crust = "#0c1312",
					text = "#e2ddc3",
					subtext1 = "#e2ddc3",
					subtext0 = "#9e9a88",
					overlay2 = "#9e9a88",
					overlay1 = "#6D9064",
					overlay0 = "#6D9064",
					surface2 = "#6D9064",
					surface1 = "#6CA08C",
					surface0 = "#6D9064",
					blue = "#6CA08C",
					lavender = "#6CA08C",
					sapphire = "#6CA08C",
					sky = "#6CA08C",
					teal = "#6CA08C",
					green = "#90B791",
					yellow = "#C9B962",
					peach = "#C9B962",
					maroon = "#9BA064",
					red = "#9e9a88",
					mauve = "#9BA064",
					pink = "#ABC894",
					flamingo = "#C9B962",
					rosewater = "#e2ddc3",
				},
			},
			styles = {
				comments = { "italic" },
				conditionals = {},
				loops = {},
				functions = {},
				keywords = {},
				strings = {},
				variables = {},
				numbers = {},
				booleans = {},
				properties = {},
				types = {},
				operators = {},
			},
		},
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "catppuccin-mocha",
		},
	},
}
